# Setup
title: after
tagline: '_'
url: https://after.dev
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Yaodong Zhao
  url: https://twitter.com/YaodongOrg
  email: yaodong@hey.com

# Custom vars
version: 3.0.0
