# Site settings
title:          "yaodong/logs"
description:    ""
url:            "https://yaodong.org"
baseurl:        "/logs"


# Author
author:
  name:         Yaodong Zhao
  url:          https://yaodong.org
  email:        yaodong@hey.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks
permalink:      /:title/
paginate:       10

# jekyll-feed
feed:
  path: feed.xml

defaults:
  - scope:
      path: '_posts'
      type: 'posts'
    values:
      layout: 'post'

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock

disqus: yaodong
